-- Generated by PCC
-- Engine: PCC-ENGINE-V7A-R1
-- Version: PCC-BUILD-V7A-R1

create table if not exists voice_engine_schema (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  status text not null default 'ACTIVE',
  meta jsonb not null default '{}'::jsonb
);